framework:
  serializer:
    enabled: true

sensio_framework_extra:
  view: { annotations: false }
  request: { converters: true }

fos_rest:
  param_fetcher_listener: true
  body_listener: true
  format_listener: true
  body_converter:
    enabled: true
  view:
    formats: { json: true, xml: false, rss: false }
  serializer:
    serialize_null: true

